name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.3] # This should match the Python version installed on EC2

    steps:
      - uses: actions/checkout@v4

      - name: Check Python Version
        run: python3 --version # Verify the Python version available on the runner

      # - name: Install Dependencies
      #   run: |
      #     python3 -m pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: Run Tests
        run: |
          python3 manage.py test
